//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restaurant()
        {
            this.RestaurantBooking = new HashSet<RestaurantBooking>();
            this.RestaurantMenu = new HashSet<RestaurantMenu>();
            this.RestaurantPic = new HashSet<RestaurantPic>();
            this.RestaurantReview = new HashSet<RestaurantReview>();
            this.RestaurantTag = new HashSet<RestaurantTag>();
        }
    
        public System.Guid Id { get; set; }
        public int Seq { get; set; }
        public string Name { get; set; }
        public System.Guid KindOfFoodId { get; set; }
        public Nullable<System.Guid> CategoryId { get; set; }
        public Nullable<System.Guid> CountryId { get; set; }
        public string Picture { get; set; }
        public bool Enabled { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedByUserId { get; set; }
        public string Description { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Country Country { get; set; }
        public virtual KindOfFood KindOfFood { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RestaurantBooking> RestaurantBooking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RestaurantMenu> RestaurantMenu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RestaurantPic> RestaurantPic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RestaurantReview> RestaurantReview { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RestaurantTag> RestaurantTag { get; set; }
    }
}
